version: '3.3'
services:
  web:
    image: feloeht/controverse-ogm:latest
    ports:
     - 30080:80
     - 30443:443
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
